### PR TITLE
Make parsing of translate tables in tree blocks more robust

### PR DESCRIPTION
**Pull request by SimonGreenhill**
This PR fixes a bug where trees with a translation block ignored taxa with asterisks in their name. These taxa labels would be silently ignored, i.e.

```
#nexus
begin trees;
	translate
		1 Simon,
		2 *Russell,
		3 Robert,
		tree tree = (1,2,3);
end;
```

..would mean that the taxon "*Russell" would be lost, and the tree would look like (Simon,2,Robert).

I believe that asterisks are invalid in taxa names anyway, but they are found in the wild (e.g. Grollemund's Bantu dataset).

It might be better to fix the bigger issue -- the translate table should not be able to have a different number of taxa in it to those in the trees. But I could not see an easy way to enforce this.

### CODE REVIEW

**Comment by SimonGreenhill** [comment]
ahh, figured out a way to check for this. We now raise an exception in `detranslate` if the Translate table doesn't match the tree.

**Comment by SimonGreenhill** [comment]
...and this popped up another bug. If there's no `translate` section in the `trees` block, we parse the first tree to identify taxa names. However this can be messed up with comments in the tree like those found [here](https://github.com/phlorest/sicoli_and_holton2014/blob/main/raw/phylogeny_deneyeniseian_24April2016.tre), e.g.:

```
...(hax[&length_mean=0.1146902001157983,height_median=2.775557561562891E-17,prob(percent)="100"...
```

where "percent" inside the comment is identified as an extra taxa. The PR now strips comments from the tree string before doing this, which is a little brute force but the comment info isn't needed here.

**Comment by xrotwang** [comment]
> ...(hax[&length_mean=0.1146902001157983,height_median=2.775557561562891E-17,prob(percent)="100"...
> ```
> 
> where "percent" inside the comment is identified as an extra taxa. The PR now strips comments from the tree string before doing this, which is a little brute force but the comment info isn't needed here.

Wow. I would have expected that braces in comments would crash the newick parsing hard. But apparently it's only square brackets that can't appear in comments ... I guess, comments in newick in Nexus is just another PHP ... and we are writing the parser ...

**Comment by xrotwang** [comment]
Ah, it does https://github.com/phlorest/sicoli_and_holton2014/blob/cd41d90973b8838879b3bcbba79c07051081745c/cldfbench_sicoli_and_holton2014.py#L7-L9
Makes me sort-of happy.

**Review by xrotwang — APPROVED** [review]

**Pull request merged**
