### PR TITLE
Remove redundant -q option

### LINKED ISSUE #19: loglevel.WARN not handled in `trees` subcommand?
The `trees` command says that to remove logging output (e.g. when piping):

```
To prevent log messages messing up the output, set '--log-level=WARN'.
```

... but this doesn't work i.e parser needs to have log-level added. I'm not sure the best way to do this? 

Also, there's a --quiet flag:

```
    parser.add_argument(
        "-q", "--quiet", dest="quiet",
        action="store_true", default=False,
        help="Be quiet (no logging information displayed)")
```

...which looks like it doesn't work. We should use either --log-level or -q, preference?

### PR DESCRIPTION
**Pull request by xrotwang**
closes #19

### CODE REVIEW

**Review by SimonGreenhill — APPROVED** [review]

**Comment by xrotwang** [comment]
Theoretically, that's a backwards incompatible change. But considering that `-q` did **nothing** previously, it could be considered a bugfix, too :)

**Comment by SimonGreenhill** [comment]
why not both! :)

**Comment by xrotwang** [comment]
So, increment both, major and patch version for a release ? :)

**Comment by SimonGreenhill** [comment]
If someone was using `-q` they'd still get the behavior they expected before and after this patch, so we should be ok!

**Pull request merged**
